[package]
name = "desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = { version = "0.1.0", path = "../../crates/audio" }
dotenvy = "0.15.7"
stt-pulse = { version = "0.1.0", path = "../../crates/stt-pulse" }
tinyvox-engine = { version = "0.1.0", path = "../../crates/engine" }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
win = { version = "0.1.0", path = "../../crates/win" }
